name: mycashbook
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  currency_text_input_formatter: ^2.1.10
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  formz: ^0.6.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
